name: mock_tests
description: comprehensive mobile learning platform that combines interactive quizzes, study guides, and personalized recommendations to enhance knowledge acquisition and skill development. With a user-friendly interface and engaging features, users can access educational resources, track progress, and collaborate with others, making learning an enjoyable and effective experience.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  http: ^1.1.0
  shared_preferences: ^2.2.1
  jwt_decoder: ^2.0.1
  local_session_timeout: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
